### ISSUE TITLE
RepairLLaMa fails to output fix to defect

### ISSUE THREAD

**Issue by ToolmanInside** [ASSERT-KTH/repairllama#2]
Hi, I am trying to running RepairLLaMa to fix bugs. But in some cases, the model fails to output patches.

For example, for the code examples in flacoco https://github.com/ASSERT-KTH/flacoco/tree/master/examples/exampleFL11/FLtest1,

the flacoco reports 5 bugs, but RepairLLaMa only outputs patches for 2 of them.

Can you check this issue for me? Thanks!

**Comment by TomasAndersonFang** [comment]
Hi @ToolmanInside,

Thanks for your interest in our work. Could you share the code examples that RepairLLaMA failed to generate patches? I'll reproduce your results and check the potential problems.

**Comment by andre15silva** [comment]
In addition to @TomasAndersonFang's question, could you let us know how you are running RepairLLaMA?

Are you using the code under `tool` or the code under `src`?

**Comment by ToolmanInside** [comment]
> Hi @ToolmanInside,
> 
> Thanks for your interest in our work. Could you share the code examples that RepairLLaMA failed to generate patches? I'll reproduce your results and check the potential problems.

Thanks for reply! 

The code example used in my experiments is from https://github.com/ASSERT-KTH/flacoco/tree/master/examples/exampleFL11/FLtest1. You can check it in this address.

When running repairllama, the tool seems firstly using flacoco to scan bugs. Here in this example, I got 5 bug reports:

Bug 01:
```java
public int calculate(String op, int op1, int op2) {

                if (op.equals("+")) {
                        return op1 + op2;
                } else if (op.equals("-")) {
                        return op1 - op2;
// buggy lines start:
                } else if (op.equals("*")) {
// buggy lines end
                        return op1 / op2;//buggy
                } else if (op.equals("/")) {
                        return op1 * op2;//buggy
                } else if (op.equals("%")) {
                        return op1 % op2;
                }
                throw new UnsupportedOperationException(op);
        }// fixed lines:
```
Bug 02:
```java
public int calculate(String op, int op1, int op2) {

                if (op.equals("+")) {
                        return op1 + op2;
// buggy lines start:
                } else if (op.equals("-")) {
// buggy lines end
                        return op1 - op2;
                } else if (op.equals("*")) {
                        return op1 / op2;//buggy
                } else if (op.equals("/")) {
                        return op1 * op2;//buggy
                } else if (op.equals("%")) {
                        return op1 % op2;
                }
                throw new UnsupportedOperationException(op);
        }// fixed lines:
```
Bug 03:
```java
// buggy lines start:
public Calculator() {
// buggy lines end
        }// fixed lines:
```
Bug 04:
```java
public Calculator() {
// buggy lines start:
        }// buggy lines end
// fixed lines:
```
Bug 05:
```java
public int calculate(String op, int op1, int op2) {

// buggy lines start:
                if (op.equals("+")) {
// buggy lines end
                        return op1 + op2;
                } else if (op.equals("-")) {
                        return op1 - op2;
                } else if (op.equals("*")) {
                        return op1 / op2;//buggy
                } else if (op.equals("/")) {
                        return op1 * op2;//buggy
                } else if (op.equals("%")) {
                        return op1 % op2;
                }
                throw new UnsupportedOperationException(op);
        }// fixed lines:
```

And then the repairllama seems running models to generate patches to above bugs. Here are what I got:

Patch 01
```java
--- fr/spoonlabs/FLtest1/Calculator.java
+++ fr/spoonlabs/FLtest1/Calculator.java
@@ -11,7 +11,7 @@
 			return op1 + op2;
 		} else if (op.equals("-")) {
 			return op1 - op2;
-		} else if (op.equals("*")) {
+		} else if (op.equals("/")) {
 			return op1 / op2;//buggy
 		} else if (op.equals("/")) {
 			return op1 * op2;//buggy
```

Patch 02
```java
// nothing
```

Patch 03
```java
// nothing
```

Patch 04
```java
--- fr/spoonlabs/FLtest1/Calculator.java
+++ fr/spoonlabs/FLtest1/Calculator.java
@@ -3,7 +3,7 @@
 public class Calculator {
 
 	public Calculator() {
-	}
+}
 
 	public int calculate(String op, int op1, int op2) {
```

Patch 05
```java
//nothing
```

**Comment by ToolmanInside** [comment]
> In addition to @TomasAndersonFang's question, could you let us know how you are running RepairLLaMA?
> 
> Are you using the code under `tool` or the code under `src`?

I followed the instructions in deployment by Docker. And yes, I used code under `tool` folder.

**Comment by andre15silva** [comment]
I see @ToolmanInside!

Unfortunately, the code under `tool` is outdated. It is the tool submitted to the APR competition (https://apr-comp.github.io/) and features an early prototype of RepairLLaMA that targets only single-line bugs.

I recommend you use the code under `src` which does not use fault localization, but rather assumes knowledge of fault localization information as described in the arxiv paper. For this code you have to construct the prompts yourself following the input representation IR4.

Sorry for the confusion! Let me know if you have any further question :)

**Comment by TomasAndersonFang** [comment]
HI @ToolmanInside,

As @andre15silva said, the reason is that the prompt you used is not what we use for RepairLLaMA (we only share RepairLLaMA trained by our best design). You can refer to our [paper](https://arxiv.org/abs/2312.15698) to build the corresponding prompt. BTW, if you also want to use the prompt you used now, we can also share the model with you.

Additionally, @andre15silva could you move the APR competition to another project since it seems to cause some confusion to others?

**Comment by ToolmanInside** [comment]
> HI @ToolmanInside,
> 
> As @andre15silva said, the reason is that the prompt you used is not what we use for RepairLLaMA (we only share RepairLLaMA trained by our best design). You can refer to our [paper](https://arxiv.org/abs/2312.15698) to build the corresponding prompt. BTW, if you also want to use the prompt you used now, we can also share the model with you.
> 
> Additionally, @andre15silva could you move the APR competition to another project since it seems to cause some confusion to others?

Thanks for quick reply!

 I now understand files under `tool` are outdated and I am trying to run scripts under `src`. But I found some data is not provided, including `data_path` and `test_file` in `llama_pred.py`. Meanwhile no instruction is provided to run this script so I have no clues to handle this part.

Can you add necessary instructions to run the scripts and provide a code example for quick demonstration?

Thanks!

**Comment by TomasAndersonFang** [comment]
> Can you add necessary instructions to run the scripts and provide a code example for quick demonstration?

I added a [jupyter notebook](https://github.com/ASSERT-KTH/repairllama/blob/main/example/example.ipynb) and used bug 05 you provided as an example. I let RepairLLaMA generate 10 patches for this bug, and you can see the first one is empty. It means that RepairLLaMA thinks we can fix this bug by removing the buggy lines. To be honest, it likes to generate such empty patches sometimes, and I guess the reason is such a fixed pattern is easy to learn in fine-tuning.

About some parameters like `data_path` and `test_file`, the former means the dir stores the `test_file`, and the latter means your personal data file that stores buggy functions built as our input representation.

If you have more questions, please let us know~
