### ISSUE TITLE
code llama vs elinas/llama-7b-hf-transformers-4.29

### ISSUE THREAD

**Issue by monilouise** [ASSERT-KTH/repairllama#6]
Hi,

First of all, congrats for the work!

I noticed you don't specify the codellama model in src/Lora/run_llama_sft.sh, and you set elinas/llama-7b-hf-transformers-4.29 as the default model in the code.  But elinas/llama-7b-hf-transformers-4.29 is not derived from codellama/CodeLlama-7b-hf.  

So, to confirm: are the results reported in the paper derived from codellama or elinas/llama-7b-hf-transformers-4.29 ?

**Comment by TomasAndersonFang** [comment]
Hi,

I'm sorry for this mistake and thanks for your reminder. I updated the source of codellama we used in our experiments.

Change elinas/llama-7b-hf-transformers-4.29 to TheBloke/CodeLlama-7B-fp16.
